
package de.dialogika.planets.planets_webservice.genericmigration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GenericMigrationSoap", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenericMigrationSoap {


    /**
     * 
     * @param parameters
     * @param binary
     * @return
     *     returns de.dialogika.planets.planets_webservice.genericmigration.MigrateOneBinaryResult
     */
    @WebMethod(action = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration/migrateOneBinary")
    @WebResult(name = "migrateOneBinaryResult", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration")
    @RequestWrapper(localName = "migrateOneBinary", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration", className = "de.dialogika.planets.planets_webservice.genericmigration.MigrateOneBinary")
    @ResponseWrapper(localName = "migrateOneBinaryResponse", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration", className = "de.dialogika.planets.planets_webservice.genericmigration.MigrateOneBinaryResponse")
    public MigrateOneBinaryResult migrateOneBinary(
        @WebParam(name = "binary", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration")
        byte[] binary,
        @WebParam(name = "parameters", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration")
        ArrayOfParameter parameters);

    /**
     * 
     * @return
     *     returns de.dialogika.planets.planets_webservice.genericmigration.ArrayOfString
     */
    @WebMethod(operationName = "GetAllTypes", action = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration/GetAllTypes")
    @WebResult(name = "GetAllTypesResult", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration")
    @RequestWrapper(localName = "GetAllTypes", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration", className = "de.dialogika.planets.planets_webservice.genericmigration.GetAllTypes")
    @ResponseWrapper(localName = "GetAllTypesResponse", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration", className = "de.dialogika.planets.planets_webservice.genericmigration.GetAllTypesResponse")
    public ArrayOfString getAllTypes();

    /**
     * 
     * @param intype
     * @return
     *     returns de.dialogika.planets.planets_webservice.genericmigration.ArrayOfString
     */
    @WebMethod(operationName = "GetMatchingOutType", action = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration/GetMatchingOutType")
    @WebResult(name = "GetMatchingOutTypeResult", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration")
    @RequestWrapper(localName = "GetMatchingOutType", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration", className = "de.dialogika.planets.planets_webservice.genericmigration.GetMatchingOutType")
    @ResponseWrapper(localName = "GetMatchingOutTypeResponse", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration", className = "de.dialogika.planets.planets_webservice.genericmigration.GetMatchingOutTypeResponse")
    public ArrayOfString getMatchingOutType(
        @WebParam(name = "intype", targetNamespace = "http://www.dialogika.de/Planets/planets.webservice/GenericMigration")
        String intype);

}
