/*
 * ConversionResult.java
 *
 * Created on 29 June 2007, 10:27
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

package eu.planets_project.ifr.core.services.migration.openXML.common;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.28 at 02:39:04 PM BST 
//

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}code"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}desc"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "result", propOrder = {
    "code",
    "desc"
})
@XmlRootElement(name = "result")
public class ConversionResult {

    @XmlElement(required = true, name="code")
    protected int code;
    @XmlElement(required = true, name="description")
    protected String desc;

    /**
     * Default constructor, assumes successful result
     */
    public ConversionResult() {
       code = 0;
       desc = "Success";
    }
    
    /**
     * Second constructor, set the code and the description
     * @param codeVal 
     * @param descVal 
     */
    public ConversionResult(int codeVal, String descVal)
    {
        code = codeVal;
        desc = descVal;
    }
    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *     
     */
    public int getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * @param codeVal 
     *     
     */
    public void setCode(int codeVal) {
        this.code = codeVal;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public String getDescription() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * @param descVal 
     *     
     */
    public void setDescription(String descVal) {
        this.desc = descVal;
    }

}
