/*
 * ConvertedFileInfo.java
 *
 * Created on 29 June 2007, 10:40
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

package eu.planets_project.ifr.core.services.migration.openXML.common;

/**
 *
 * @author CFwilson
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.28 at 02:39:04 PM BST 
//
import java.util.Date;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}inputsize"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}outputsize"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}pages"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}creator"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}title"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}subject"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}keywords"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}description"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}lastModifiedBy"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}revision"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}created"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}modified"/>
 *         &lt;element ref="{http://www.planets-project.eu/xml/ns/planets/services/odfInfo}company"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputSize",
    "outputSize",
    "pages",
    "words",
    "characters",
    "lines",
    "paragraphs",
    "charactersWithSpaces",
    "creator",
    "title",
    "subject",
    "keywords",
    "lastModifiedBy",
    "revision",
    "created",
    "modified",
    "company"
})
@XmlRootElement(name = "fileInfo")
public class ConvertedFileInfo {

    @XmlElement(required = true, name="inputSize")
    protected int inputSize = 0;
    @XmlElement(required = true, name="outputSize")
    protected int outputSize = 0;
    @XmlElement(required = true, name="pages")
    protected int pages = 0;
    @XmlElement(required = true, name="words")
    protected int words = 0;
    @XmlElement(required = true, name="characters")
    protected int characters = 0;
    @XmlElement(required = true, name="lines")
    protected int lines = 0;
    @XmlElement(required = true, name="paragraphs")
    protected int paragraphs = 0;
    @XmlElement(required = true, name="charactersWithSpaces")
    protected int charactersWithSpaces = 0;
    @XmlElement(required = true, name="creator")
    protected String creator = "";
    @XmlElement(required = true, name="title")
    protected String title = "";
    @XmlElement(required = true, name="subject")
    protected String subject = "";
    @XmlElement(required = true, name="keywords")
    protected String keywords = "";
    @XmlElement(required = true, name="lastModifiedBy")
    protected String lastModifiedBy = "";
    @XmlElement(required = true, name="")
    protected int revision = 0;
    @XmlElement(required = true, name="created")
    protected Date created = new Date();
    @XmlElement(required = true, name="modified")
    protected Date modified = new Date();
    @XmlElement(required = true, name="company")
    protected String company = "";

    /**
     * Gets the value of the inputsize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getInputSize() {
        return inputSize;
    }

    /**
     * Sets the value of the inputsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInputSize(int inputSizeVal) {
        this.inputSize = inputSizeVal;
    }

    /**
     * Gets the value of the outputsize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getOutputSize() {
        return outputSize;
    }

    /**
     * Sets the value of the outputsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOutputSize(int outputSizeVal) {
        this.outputSize = outputSizeVal;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPages(int pagesVal) {
        this.pages = pagesVal;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreator(String creatorVal) {
        this.creator = creatorVal;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String titleVal) {
        this.title = titleVal;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String subjectVal) {
        this.subject = subjectVal;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeywords(String keywordsVal) {
        this.keywords = keywordsVal;
    }

    /**
     * Gets the value of the lastModifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * Sets the value of the lastModifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModifiedBy(String lastModifiedVal) {
        this.lastModifiedBy = lastModifiedVal;
    }

    /**
     * Gets the value of the revision property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public int getRevision() {
        return revision;
    }

    /**
     * Sets the value of the revision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRevision(int revisionVal) {
        this.revision = revisionVal;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreated(Date createdVal) {
        this.created = createdVal;
    }

    /**
     * Gets the value of the modified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModified(Date modifiedVal) {
        this.modified = modifiedVal;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompany(String companyVal) {
        this.company = companyVal;
    }

}
